cluster.name: ${cluster.name}
node.name: ${HOSTNAME}

network.host: 0.0.0.0
network.publish_host: ${network.publish_host}
transport.publish_port: ${transport.publish_port}
#network.bind_host: [_local_, _eth0_]

http.port: 9200
transport.tcp.port: 9300

discovery.zen.ping.unicast.hosts: ${discovery.zen.ping.unicast.hosts}

# (master_eligible_nodes / 2) + 1
discovery.zen.minimum_master_nodes: ${discovery.zen.minimum_master_nodes}

bootstrap.memory_lock: true

#index.mapper.dynamic: false

http.cors.enabled: true
http.cors.allow-origin: "*"

indices.fielddata.cache.size: 20%

path.repo: ["/usr/share/elasticsearch/backups"]

xpack.ssl.key:                     ${ES_HOME}/config/ssl/node1.key
xpack.ssl.certificate:             ${ES_HOME}/config/ssl/node1.crt
xpack.ssl.certificate_authorities: [ "${ES_HOME}/config/ssl/ca.crt" ]

# enable tls/ssl connection
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.enabled: false

# disable ca verification
xpack.ssl.verification_mode: none
xpack.ssl.client_authentication: none

xpack.security.audit.enabled: false
xpack.security.audit.outputs: [ logfile, index ]
xpack.security.audit.index.events.exclude: [ access_granted, authentication_success ]
xpack.security.audit.logfile.events.exclude: [ access_granted, authentication_success ]

xpack.monitoring.collection.interval: 30s
xpack.monitoring.history.duration: 1d

#xpack.monitoring.enabled: false
#xpack.graph.enabled: false
#xpack.watcher.enabled: false